######################################
######################################
prefix dcterm: <http://purl.org/dc/terms/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dcty: <http://purl.org/dc/dcmitype/>

#select ?s ?p ?o
select ?title ?subject
{
  ?title bds:search "agric*" .
  ?s dcterm:type dcty:Text;
     dc:title ?title .
  ?s dc:subject ?c .
  ?c skos:prefLabel ?subject.
  FILTER(LANG(?subject) = 'en')
}
LIMIT 100